### ISSUE TITLE
PHP 7.3 - Server dashboard response for servers not empty

### ISSUE THREAD

**Issue by elitetheespeon** [OpenGamePanel/OGP-Website#481]
I have recently upgraded from PHP 5.6 to PHP 7.3 and everything works except for the Dashboard page. When a server has any players, it creates the following PHP error:
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function print_player_list(), 3 passed in .../protocol/lgsl/LGSLMonitor.php on line 72 and exactly 4 expected in .../modules/dashboard/query_ref.php:25
Stack trace:
#0 ...protocol/lgsl/LGSLMonitor.php(72): print_player_list(Array, 3, 30)
#1 .../modules/dashboard/query_ref.php(76): require('...')
#2 .../includes/navig.php(106): exec_ogp_module()
#3 .../includes/navig.php(27): navigation()
#4 .../home.php(146): include('...')
#5 .../home.php(71): heading(true)
#6 {main}
  thrown in ...modules/dashboard/query_ref.php on line 25
```

**Comment by own3mall** [comment]
Should be fixed now.  Thanks for reporting.

**Comment by own3mall** [comment]
https://stackoverflow.com/questions/4697705/php-function-overloading
