### ISSUE TITLE
Issue in Game Monitor if game server has no IP:PORT set (or MOD set)

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#612]
Opening the issue, will update with info as they come, current situation:

https://opengamepanel.org/forum/viewthread.php?thread_id=8161&pid=42022#post_42022

Basically, on a fresh Panel installation Ubuntu 22 with PHP 8.1 (did not test with other OS and PHP version), create one game server in your Panel (Killing Floor 2), do not set the IP:PORT, Game Monitor is broken.
Add the IP:PORT, Game Monitor is not broken.
If you create multiple game servers and none has an IP:PORT set, it is broken. Set the IP:PORT in only one of the game servers created, then it is not broken.

The same issue with the MOD, create one game server requiring to have the MOD set (7 Day to Die), do not set the IP:PORT, Game Monitor is broken. Add the IP:PORT, Game Monitor is still broken. Eventually, set the MOD too, it is not broken anymore.
Same thing, if you create multiple servers requiring to set IP:PORT and the MOD, then as soon as only one has IP:PORT and MOD set, Game Monitor is not broken anymore.

log example:

```
[Sun Sep 17 17:39:00.635057 2023] [php:error] [pid 5338] [client 127.0.0.1:51842] PHP Fatal error:  Uncaught TypeError: array_multisort(): Argument #1 ($array) must be an array or a sort flag in /var/www/html/includes/functions.php:231\nStack trace:\n#0 /var/www/html/includes/functions.php(231): array_multisort()\n#1 /var/www/html/modules/gamemanager/server_monitor.php(241): create_home_selector_address()\n#2 /var/www/html/includes/navig.php(106): exec_ogp_module()\n#3 /var/www/html/includes/navig.php(27): navigation()\n#4 /var/www/html/home.php(146): include('...')\n#5 /var/www/html/home.php(405): heading()\n#6 /var/www/html/home.php(77): ogpHome()\n#7 {main}\n  thrown in /var/www/html/includes/functions.php on line 231, referer: http://localhost/home.php?m=dashboard&p=dashboard
[Sun Sep 17 17:49:11.210711 2023] [php:error] [pid 7046] [client 127.0.0.1:45840] PHP Fatal error:  Uncaught TypeError: array_multisort(): Argument #1 ($array) must be an array or a sort flag in /var/www/html/includes/functions.php:231\nStack trace:\n#0 /var/www/html/includes/functions.php(231): array_multisort()\n#1 /var/www/html/modules/gamemanager/server_monitor.php(241): create_home_selector_address()\n#2 /var/www/html/includes/navig.php(106): exec_ogp_module()\n#3 /var/www/html/includes/navig.php(27): navigation()\n#4 /var/www/html/home.php(146): include('...')\n#5 /var/www/html/home.php(405): heading()\n#6 /var/www/html/home.php(77): ogpHome()\n#7 {main}\n  thrown in /var/www/html/includes/functions.php on line 231, referer: http://localhost/home.php?m=dashboard&p=dashboard

```

I could swear that before, if you didn't set the IP:PORT or MOD, it would spit a message regarding that. It actually still does, if you have at least one game server properly set with IP:PORT and MOD.

**Comment by DieFeM** [comment]
At this function:
https://github.com/OpenGamePanel/OGP-Website/blob/master/includes/functions.php#L198C1-L252C2

There's a loop which, in order to sort the array, descomposes the servers array in to smaller arrays of its keys, skipping those servers which doesn't contain mod_id or ip keys. Therefore, if there's no servers after this operation, the smaller arrays do not exist. The solution would be iterating the servers array in first place, and check the key arrays before continuing with the execution of the function.

```
function create_home_selector_address($module, $subpage, $server_homes, $extra_inputs = FALSE, $method = "GET") {
	$home_name = array();
	$home_id = array();
	$mod_id = array();
	$ip = array();
	$port = array();
	foreach ($server_homes as $key => $row) {
		if( !isset($row['ip']) or !isset($row['mod_id']) )
		{
			unset($server_homes[$key]);
			continue;
		}
		$home_name[$key] = $row['home_name'];
		$home_id[$key] = $row['home_id'];
		$mod_id[$key] = $row['home_id'];
		$ip[$key] = $row['ip'];
		$port[$key] = $row['port'];
	}
	
	# Make sure it has at least one server with ip and mod.
	if (empty($home_name))
	{
		return
	}
	
	if( isset($_GET['home_id-mod_id-ip-port']) and $_GET['home_id-mod_id-ip-port'] != "" )
	{
		list($get_home_id,
			 $get_mod_id,
			 $get_ip,
			 $get_port) = explode( "-", $_GET['home_id-mod_id-ip-port'] );
	}
	echo "<form method='$method' name='select' action=''>\n";
	echo "<input type='hidden' name='m' value='$module' />\n";
	if( $subpage ) echo "<input type='hidden' name='p' value='".$subpage."' />\n";
	if($extra_inputs)
	{
		foreach($extra_inputs as $input)
		{
			echo "<input type='" . $input['type'] . "' name='" . $input['name'] . "' value='" . $input['value'] . "' />\n";
		}
	}
	echo "<select onchange=\"this.form.submit();\" name='home_id-mod_id-ip-port'>\n";
	echo "<option></option>\n";
	array_multisort($home_name, $ip, $port, $mod_id, 
					$home_id, SORT_DESC, $server_homes);
	foreach ( $server_homes as $server_home )
	{
		$display_ip = checkDisplayPublicIP($server_home['display_public_ip'],$server_home['ip'] != $server_home['agent_ip'] ? $server_home['ip'] : $server_home['agent_ip']);

		if(isset($_GET['home_id-mod_id-ip-port']) and 
		   $get_home_id == $server_home['home_id'] and 
		   $get_mod_id == $server_home['mod_id'] and 
		   $get_ip == $server_home['ip'] and 
		   $get_port == $server_home['port'])
			$selected = 'selected="selected"';
		else
			$selected = '';
		echo "<option value='". $server_home['home_id'] .
			 "-" . $server_home['mod_id'] . "-" . $server_home['ip'] . 
			 "-" . $server_home['port'] . "' $selected >" . 
			 htmlentities($server_home['home_name']) . " - " . $display_ip .
			 ":" . $server_home['port'] . "</option>\n";
	}
	echo "</select>\n";
	echo "</form>";	
}
```

**Comment by own3mall** [comment]
@DieFeM thanks for the fix :+1:

**Comment by Zorrototo** [comment]
Thanks mates! :+1:

**Comment by DieFeM** [comment]
No problem, thank you too, for compiling the issue and actually testing and publishing the solution.
![image](https://github.com/OpenGamePanel/OGP-Website/assets/6736736/eab7af61-2ebf-4923-932f-cfaf4ef962b1)
